src/Entity/Site.php
<?php

namespace App\Entity;

use App\Repository\SiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SiteRepository::class)]
class Site
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $source_url;

    #[ORM\Column(type: 'datetime')]
    private $creates_at;

    #[ORM\OneToMany(mappedBy: 'site', targetEntity: Follow::class)]
    private $follows;

    public function __construct()
    {
        $this->follows = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSourceUrl(): ?string
    {
        return $this->source_url;
    }

    public function setSourceUrl(string $source_url): self
    {
        $this->source_url = $source_url;

        return $this;
    }

    public function getCreatesAt(): ?\DateTimeInterface
    {
        return $this->creates_at;
    }

    public function setCreatesAt(\DateTimeInterface $creates_at): self
    {
        $this->creates_at = $creates_at;

        return $this;
    }

    /**
     * @return Collection|Follow[]
     */
    public function getFollows(): Collection
    {
        return $this->follows;
    }

    public function addFollow(Follow $follow): self
    {
        if (!$this->follows->contains($follow)) {
            $this->follows[] = $follow;
            $follow->setSite($this);
        }

        return $this;
    }

    public function removeFollow(Follow $follow): self
    {
        if ($this->follows->removeElement($follow)) {
            // set the owning side to null (unless already changed)
            if ($follow->getSite() === $this) {
                $follow->setSite(null);
            }
        }

        return $this;
    }
}

src/Form/SiteType.php
<?php

namespace App\Form;

use App\Entity\Site;
use DateTime;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('source_url');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Site::class,
        ]);
    }
}

src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Entity\Site;
use App\Form\SiteType;
use App\Repository\SiteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/site')]
class SiteController extends AbstractController
{
    #[Route('/', name: 'site_index', methods: ['GET'])]
    public function index(SiteRepository $siteRepository): Response
    {
        
        return $this->render('site/index.html.twig', [
            'sites' => $siteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'site_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $site = new Site();
        $form = $this->createForm(SiteType::class, $site);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($site);
            $entityManager->flush();

            return $this->redirectToRoute('site_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('site/new.html.twig', [
            'site' => $site,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'site_show', methods: ['GET'])]
    public function show(Site $site): Response
    {
        return $this->render('site/show.html.twig', [
            'site' => $site,
        ]);
    }

    #[Route('/{id}/edit', name: 'site_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Site $site, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SiteType::class, $site);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('site_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('site/edit.html.twig', [
            'site' => $site,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'site_delete', methods: ['POST'])]
    public function delete(Request $request, Site $site, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$site->getId(), $request->request->get('_token'))) {
            $entityManager->remove($site);
            $entityManager->flush();
        }

        return $this->redirectToRoute('site_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/site/_delete_form.html.twig
<form method="post" action="{{ path('site_delete', {'id': site.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ site.id) }}">
    <button class="btn">Delete</button>
</form>

templates/site/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/site/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Site{% endblock %}

{% block body %}
    <h1>Edit Site</h1>

    {{ include('site/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('site_index') }}">back to list</a>

    {{ include('site/_delete_form.html.twig') }}
{% endblock %}

templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Site index{% endblock %}

{% block body %}
    <h1>Site index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Source_url</th>
                <th>Creates_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for site in sites %}
            <tr>
                <td>{{ site.id }}</td>
                <td>{{ site.name }}</td>
                <td>{{ site.description }}</td>
                <td>{{ site.sourceUrl }}</td>
                <td>{{ site.createsAt ? site.createsAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('site_show', {'id': site.id}) }}">show</a>
                    <a href="{{ path('site_edit', {'id': site.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('site_new') }}">Create new</a>
{% endblock %}

templates/site/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Site{% endblock %}

{% block body %}

    <h1>Ajouter un nouveau flux à ma liste</h1>

    {{ include('site/_form.html.twig') }}

    <a href="{{ path('espace') }}">Terminer</a>
{% endblock %}

templates/site/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Site{% endblock %}

{% block body %}
    <h1>Site</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ site.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ site.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ site.description }}</td>
            </tr>
            <tr>
                <th>Source_url</th>
                <td>{{ site.sourceUrl }}</td>
            </tr>
            <tr>
                <th>Creates_at</th>
                <td>{{ site.createsAt ? site.createsAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('site_index') }}">back to list</a>

    <a href="{{ path('site_edit', {'id': site.id}) }}">edit</a>

    {{ include('site/_delete_form.html.twig') }}
{% endblock %}