src/Entity/Follow.php
<?php

namespace App\Entity;

use App\Repository\FollowRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FollowRepository::class)]
class Follow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Membre::class, inversedBy: 'follows')]
    private $user;

    #[ORM\ManyToOne(targetEntity: Site::class, inversedBy: 'follows')]
    private $site;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $categorie;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Membre
    {
        return $this->user;
    }

    public function setUser(?Membre $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(?string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(?string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }
}

templates/_footer.html.twig
<!-- Footer -->
<footer class="text-center text-white footer">
  <!-- Grid container -->
  <div class="container">
    <!-- Section: Links -->
    <section class="mt-5">
      <!-- Grid row-->
      <div class="row text-center pt-5">
          <h6 class="font-weight-bold justify-content-between">
            <a href="{{path ("contact")}}" class="text-white">Contact</a>
            <a href="{{path ("mentions_legales")}}" class="text-white">Mentions légales</a>
          </h6>
      </div>
      <!-- Grid row-->
    </section>
    <!-- Section: Links -->
    <hr class="my-5" />
    <!-- Section: Text -->
    <section class="mb-5">
      <div class="row d-flex justify-content-center">
        <div class="col-lg ">
          <p class="text-center">
              Jérôme, Xavier et Noémie une petite équipe de Webforce 3 ,présentent ce site pour rester toujours à la page de la veille technologique!
          </p>
        </div>
      </div>
    </section>
    <!-- Section: Text -->

    <!-- Section: Social -->
    <section class="text-center mb-5">
      <a href="https://fr-fr.facebook.com/" class="text-white me-4">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://twitter.com/?lang=fr" class="text-white me-4">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="https://www.google.com/" class="text-white me-4">
        <i class="fab fa-google"></i>
      </a>
      <a href="https://www.instagram.com/" class="text-white me-4">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="https://www.linkedin.com/" class="text-white me-4">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="https://github.com/" class="text-white me-4">
        <i class="fab fa-github"></i>
      </a>
    </section>
    <!-- Section: Social -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 copy">
    <a>Copyright &copy;<script>document.write(new Date().getFullYear());</script></a>
    
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
 

templates/_menu_left.html.twig
<div id="mySidepanel" class="sidepanel bg-light">
  {# Bouton burger #}
  <button  id="btn-nav" class="btn btn-outline-secondary" ><i class="fas fa-times"></i></button>
  {# Logo #}
  <a href="{{path ("home")}}"><div class="photo-profil"><img src="{{ chemin ?? '' }}./image/logo_small.png" alt="logo FeedyTech" id="img"></div></a>
  {# Dropdown menu #}
  <button class="dropdown-btn">Mes flux <i class="fas fa-rss"></i>
    <i class="fa fa-caret-down"></i>
  </button>
  {# Liens de flux suivis l'utilisateur #}
  <div class="dropdown-container">
    {% if follow is defined %}
      {% for site in follow %}
        <div class="d-flex justify-centent-between align-items-center">
          <a href="{{ path("espace_follow",{ id: site.id })}}" class="rounded style_hover">{{site.site.name}}</a> 
          {# Bouton delete #}
          <form method="post" action="{{ path('follow_delete', {'id': site.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer ce lien ?');">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ site.id) }}">
            <button class="btn text-danger"><i class="fas fa-times"></i></button>
          </form>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <a href=" {{path("app_logout")}} " class="rounded style_hover">Deconnexion <i class="fa fa-sign-out-alt"></i> </a>
  <button id="theme" class="btn-outline-secondary rounded style_hover ">Mode Sombre <i class="fas fa-adjust"></i></button>
</div>

templates/_message.html.twig
{% for type, messages in app.flashes %}
    {% for msg in messages %}
        <div class="alert alert-{{ type }}">{{ msg|raw }}</div>
    {% endfor %}
{% endfor %}

templates/_nav_espace.html.twig
{# Navbar dans la page mon espace #}
<nav class="navbar navbar-expand navbar-light fixed-top bg-light menu_top ">
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav w-25 justify-content-start">
      <li class="nav-item d-flex justify-content_between align-items-center" id="li-ouv">
        <button class="btn btn-outline-secondary" id="btn-nav-open" >&#9776;</button>  
        {# Logo #}
        <a href="{{path ("home")}}"><div class="photo-profil" id="logo"><img src="{{ chemin ?? '' }}./image/logo_small.png"  id="logo2" alt="logo FeedyTech"></div></a>
      </li>
      </ul>
      <ul class="navbar-nav w-75 justify-content-around">
      <li class="nav-item ">
        <a class="nav-link deco_menu " href=" {{ path("espace") }} ">Mon espace <i class="fa fa-user"></i></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link deco_menu" href="{{ path("espace")}}#ajouter">Rechercher un nouveau flux <i class="fas fa-search"></i></a>
      </li>
    </ul>
  </div>
</nav>

templates/_non_connecte.html.twig
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
	<div class="container">
		<div class="d-flex align-items-center justify-content-between w-100">
			<a class="navbar-brand" href="{{path ("home")}}">
				<img src="../image/logo_small.png" class="w-50 h-3 m-auto logo-nav" alt="logo de feedytech" ></a>
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon text-white"></span>
			</button>
		</div>
		<div class="collapse navbar-collapse text-white" id="navbarCollapse">
			<ul class="navbar-nav ms-auto mb-2 mb-lg-0" id="liens">	
				<li class="nav-item mr-1">
					<a href="{{path ("home")}}" class="btn px-3 me-2 nav-link text-white d-flex align-items-center ">Accueil <i class="fas fa-home ms-1"></i></a>
				</li>
				{% if is_granted("ROLE_USER") %}
				<li class="nav-item mr-1">
					<a href="{{path ("app_logout")}}" class="btn me-2 nav-link text-white d-flex align-items-center">Deconnexion <i class="fa fa-sign-out-alt ms-1"></i> </a>
				</li>
				{% else %}
				<li class="nav-item mr-1">
					<a href="{{path ("app_login")}}" class="btn me-2 nav-link text-white d-flex align-items-center">Connexion <i class="fa fa-sign-in-alt ms-1"></i></a>
				</li>
				{% endif %}
			</ul>
		</div>
	<!--/.nav-collapse -->
	</div>
</nav>

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}FeedyTech!{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" href="../image/logo_small.ico" type="image/x-icon">    
    {# CDN Bootstrap #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }} 
        {{ encore_entry_link_tags('register') }}
    {% endblock %}
</head>
<body> 
    {# Inclusion du menu #}
	{% include "_non_connecte.html.twig" %}
    <div class="main">
        {% block body %}        
            {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            {% endblock %}
                
        {% endblock %}
    </div>
    <div>
        {% include "_footer.html.twig" %}
    </div>

    
    {# Script cookies #}
    <script src="/js/cookiechoices.js"></script><script>document.addEventListener('DOMContentLoaded', function(event){cookieChoices.showCookieConsentBar('Ce site utilise des cookies pour vous offrir le meilleur service. En poursuivant votre navigation, vous acceptez l’utilisation des cookies.', 'J’accepte', 'En savoir plus', 'mentions-legales');});</script>
    {# Script bundle Bootstrap #}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>